help:
	# usage: make build|build-free

build:
	../puavo-patch/bin/patch-stretch.sh stretch|tee build-stretch.log

build-free:
	../puavo-patch/bin/patch-stretch stretch free|tee build-stretch-free.log



